fix: pin protobuf version during build
bigmlcom/sensenet pull request #39
Opened 2022-08-17 11:43 UTC by aclementev

Due to a breaking change in protobuf, we need to make sure to not use
a too recent version of the library when installing "older" versions
of tensorflow.
This was documented [here](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates)

This was breaking the installation process, at least on mac m1. 
If someone can test it on a different arch, we can make sure this works on other archs as well.

2022-08-18 14:01 UTC, charleslparker requested changes
@aclementev - If this fixes the issue you were having, I will take your word for it that this is the right fix (I can't really test anything because I don't have access to apple silicon).  

Wheels are built using Github actions + Emulation + CIBuildWheel for every PR (you can see this happening if you look under "Checks" in the PR, and you can also see there the output of the build process and the rudimentary tests we run to make sure everything is working on each architecture.

If you bump the version of the library in `__init__.py`, we can push this.  The reason that the version needs to be updated is that we need to push a tag with the new version to github which will trigger the upload of the new wheels to PyPI.

2022-08-18 14:05 UTC, charleslparker commented
FYI I just saw this message in the output of the macos-arm64 run of CIBuildWheel, which is probably relevant:

```
Warning: While arm64 wheels can be built on x86_64, they cannot be tested. The ability to test the arm64 wheels will be added in a future release of cibuildwheel, once Apple Silicon CI runners are widely available. To silence this warning, set `CIBW_TEST_SKIP: *-macosx_arm64`.
```

So we're flying a bit blind at the moment with the arm64 wheels.

2022-08-18 17:30 UTC, aclementev commented
> If this fixes the issue you were having, I will take your word for it that this is the right fix (I can't really test anything because I don't have access to apple silicon).

Actually what I wanted to make sure was that this did not break a non-apple silicon as well :) 
I just tested it in a Linux VM and it seems to work in there (just a `pip install .`) which is a good sign.

I tried to run the cibuildwheel locally to check the apple silicon wheel building process, but I ran into another set of issues with `delocate`ing the resulting wheels. But that's okay for now, I don't think that's something that I introduced with this.

With that, I am moderately confident that I did not break anything extra, so I will bump the version.

2022-08-21 13:29 UTC, charleslparker commented
@aclementev - Don't know if you looked into it, but the pinned version of protobuf seems incompatible with the standard tensorflow, according to the tests.  If you want, you can try pinning this version just for M1, further down in the setup file:

https://github.com/bigmlcom/sensenet/blob/master/setup.py#L30

2024-02-13 09:38 UTC, closed without merging